name: 'Terragrunt Action'
description: 'Execute Terragrunt commands defined in a Makefile'
inputs:
  command:
    description: 'Terragrunt command to execute via Makefile target'
    required: true
    default: 'validate'
  config-paths:
    description: >-
      List of Terragrunt configuration pathname patterns separated by spaces.
      The patterns will be passed to find(1) via the "-path" primary, so they
      may contain shell wildcards. Paths are relative to the repository root.
    required: false
    default: '*'
  init:
    description: 'Whether to run "make init" before any other targets'
    required: false
    default: 'true'
  aws-access-key-id:
    description: 'IAM user access key ID to use pass to the `make` command'
    required: false
  aws-secret-access-key:
    description: 'IAM user secret access key to pass to the `make` command'
    required: false
  tfenv-version:
    description: 'Branch, tag or commit hash for tfenv'
    required: true
    default: 459d15b63f55c2f507bfa6a18e9dec5937e45daf
  tgenv-version:
    description: 'Branch, tag or commit hash for tgenv'
    required: true
    default: b71a32439f23fa7745330e48c3495c4c8a23ddf3 # v0.0.3
outputs:
  changed-paths:
    description: >-
      For the `plan` command, returns a list of Terragrunt configuration paths
      which reported changes to be applied
    value: ${{ steps.main.outputs.changed-paths }}
runs:
  using: composite
  steps:
    - run: |
        echo ::group::Clone tfenv
        git clone -q https://github.com/tfutils/tfenv.git ~/.tfenv
        git -C ~/.tfenv checkout -q ${{ inputs.tfenv-version }}
        echo "$HOME/.tfenv/bin" >> $GITHUB_PATH
        echo ::endgroup::

        echo ::group::Clone tgenv
        git clone -q https://github.com/cunymatthieu/tgenv.git ~/.tgenv
        git -C ~/.tgenv checkout -q ${{ inputs.tgenv-version }}
        echo "$HOME/.tgenv/bin" >> $GITHUB_PATH
        echo ::endgroup::

        echo ::group::Run tfenv install
        PATH="$HOME/.tfenv/bin:$PATH" tfenv install
        echo ::endgroup::

        echo ::group::Run tgenv install
        PATH="$HOME/.tgenv/bin:$PATH" tgenv install
        echo ::endgroup::
      shell: bash
    - id: main
      run: |
        if ${{ inputs.init }}; then
          echo "::group::Run make init paths='${{ inputs.config-paths }}'"
          make init paths='${{ inputs.config-paths }}' 2>&1
          echo ::endgroup::
        fi

        # When GITHUB_ACTIONS=true, this command will also write the required
        # statements to set the outputs of this GitHub action.
        make '${{ inputs.command }}' paths='${{ inputs.config-paths }}'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        TF_IN_AUTOMATION: 'true'
