name: 'Terragrunt Action'
description: 'Execute Terragrunt commands defined in a Makefile'
inputs:
  command:
    description: 'Terragrunt command to execute via Makefile target'
    required: true
    default: 'validate'
  config-paths:
    description: >-
      List of Terragrunt configuration pathname patterns separated by spaces.
      The patterns will be passed to find(1) via the "-path" primary, so they
      may contain shell wildcards. Paths are relative to the repository root.
    required: false
    default: '*'
  init:
    description: 'Whether to run "make init" before any other targets'
    required: false
    default: 'true'
  aws-access-key-id:
    description: 'IAM user access key ID to use pass to the `make` command'
    required: false
  aws-secret-access-key:
    description: 'IAM user secret access key to pass to the `make` command'
    required: false
  tfenv-version:
    description: 'Branch, tag or commit hash for tfenv'
    required: true
    default: 459d15b63f55c2f507bfa6a18e9dec5937e45daf
  tgenv-version:
    description: 'Branch, tag or commit hash for tgenv'
    required: true
    default: b71a32439f23fa7745330e48c3495c4c8a23ddf3 # v0.0.3
outputs:
  changed-paths:
    description: >-
      For the `plan` command, returns a list of Terragrunt configuration paths
      which reported changes to be applied
    value: ${{ steps.main.outputs.changed-paths }}
runs:
  using: docker
  image: ../../../.terragrunt/Dockerfile
